CREATE TABLE `books` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `author` TEXT NOT NULL,
  `launch_date` DATETIME NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `title` TEXT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
